#ifndef __KL2EDK_AUTOGEN_ViconVersion__
#define __KL2EDK_AUTOGEN_ViconVersion__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ViconVersion'
// Defined at ./ViconVersion.kl:6:1

struct ViconVersion
{
  typedef ViconVersion &Result;
  typedef ViconVersion const &INParam;
  typedef ViconVersion &IOParam;
  
  SInt32 major;
  SInt32 minor;
  SInt32 point;
};

inline void Traits<ViconVersion>::ConstructEmpty( ViconVersion &val )
{
  Traits< SInt32 >::ConstructEmpty( val.major );
  Traits< SInt32 >::ConstructEmpty( val.minor );
  Traits< SInt32 >::ConstructEmpty( val.point );
}
inline void Traits<ViconVersion>::ConstructCopy( ViconVersion &lhs, ViconVersion const &rhs )
{
  Traits< SInt32 >::ConstructCopy( lhs.major, rhs.major );
  Traits< SInt32 >::ConstructCopy( lhs.minor, rhs.minor );
  Traits< SInt32 >::ConstructCopy( lhs.point, rhs.point );
}
inline void Traits<ViconVersion>::AssignCopy( ViconVersion &lhs, ViconVersion const &rhs )
{
  Traits< SInt32 >::AssignCopy( lhs.major, rhs.major );
  Traits< SInt32 >::AssignCopy( lhs.minor, rhs.minor );
  Traits< SInt32 >::AssignCopy( lhs.point, rhs.point );
}
inline void Traits<ViconVersion>::Destruct( ViconVersion &val )
{
  Traits< SInt32 >::Destruct( val.point );
  Traits< SInt32 >::Destruct( val.minor );
  Traits< SInt32 >::Destruct( val.major );
}
}}}

#endif // __KL2EDK_AUTOGEN_ViconVersion__
