#ifndef __KL2EDK_AUTOGEN_ViconDirection__
#define __KL2EDK_AUTOGEN_ViconDirection__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ViconDirection'
// Defined at ./ViconDirection.kl:6:1

struct ViconDirection
{
  typedef ViconDirection &Result;
  typedef ViconDirection const &INParam;
  typedef ViconDirection &IOParam;
  
  Data handle;
};

inline void Traits<ViconDirection>::ConstructEmpty( ViconDirection &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<ViconDirection>::ConstructCopy( ViconDirection &lhs, ViconDirection const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<ViconDirection>::AssignCopy( ViconDirection &lhs, ViconDirection const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<ViconDirection>::Destruct( ViconDirection &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_ViconDirection__
