#ifndef __KL2EDK_AUTOGEN_ViconDirection_functions__
#define __KL2EDK_AUTOGEN_ViconDirection_functions__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "ViconDirection.h"


// Defined at ./ViconDirection.kl:11:1
FABRIC_EXT_EXPORT void ViconDirectionFromString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
);

// Defined at ./ViconDirection.kl:12:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 ViconDirectionAsCode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::INParam this_
);

// Defined at ./ViconDirection.kl:13:1
FABRIC_EXT_EXPORT void ViconDirectionAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::INParam this_
);

// Defined at ./ViconDirection.kl:14:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconDirectionEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::INParam b
);

// Defined at ./ViconDirection.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconDirectionNotEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconDirection >::INParam b
);

#endif // __KL2EDK_AUTOGEN_ViconDirection_functions__
