#ifndef __KL2EDK_AUTOGEN_ViconTimeCodeStandard_functions__
#define __KL2EDK_AUTOGEN_ViconTimeCodeStandard_functions__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "ViconTimeCodeStandard.h"


// Defined at ./ViconTimeCodeStandard.kl:11:1
FABRIC_EXT_EXPORT void ViconTimeCodeStandardFromString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
);

// Defined at ./ViconTimeCodeStandard.kl:12:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 ViconTimeCodeStandardAsCode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::INParam this_
);

// Defined at ./ViconTimeCodeStandard.kl:13:1
FABRIC_EXT_EXPORT void ViconTimeCodeStandardAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::INParam this_
);

// Defined at ./ViconTimeCodeStandard.kl:14:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconTimeCodeStandardEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::INParam b
);

// Defined at ./ViconTimeCodeStandard.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconTimeCodeStandardNotEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCodeStandard >::INParam b
);

#endif // __KL2EDK_AUTOGEN_ViconTimeCodeStandard_functions__
