#ifndef __KL2EDK_AUTOGEN_ViconTimeCodeStandard__
#define __KL2EDK_AUTOGEN_ViconTimeCodeStandard__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ViconTimeCodeStandard'
// Defined at ./ViconTimeCodeStandard.kl:6:1

struct ViconTimeCodeStandard
{
  typedef ViconTimeCodeStandard &Result;
  typedef ViconTimeCodeStandard const &INParam;
  typedef ViconTimeCodeStandard &IOParam;
  
  Data handle;
};

inline void Traits<ViconTimeCodeStandard>::ConstructEmpty( ViconTimeCodeStandard &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<ViconTimeCodeStandard>::ConstructCopy( ViconTimeCodeStandard &lhs, ViconTimeCodeStandard const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<ViconTimeCodeStandard>::AssignCopy( ViconTimeCodeStandard &lhs, ViconTimeCodeStandard const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<ViconTimeCodeStandard>::Destruct( ViconTimeCodeStandard &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_ViconTimeCodeStandard__
