/*
 * Fabric Core 1.11.4
 * Vicon Datastream EDK wrap
 */

#include "ViconResult.h" // Automatically generated by kl2edk
#include "ViconResult_functions.h"
#include <Client.h> // Vicon header
#include "conversion.h"

FABRIC_EXT_EXPORT void ViconResultFromString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
  this_.handle = new ViconDataStreamSDK::CPP::Result::Enum(StringToResultEnum(name.data()));
}

FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 ViconResultAsCode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam this_
)
{
  ViconDataStreamSDK::CPP::Result::Enum resultEnum;
  if (conv_from_KLStruct(this_, resultEnum))
  {
    return Fabric::EDK::KL::Integer(resultEnum);
  } else {
    FABRIC_EXT_SETERROR_AND_RETURN_VALUE(0, "%s: %s", "ViconResultAsCode", "Invalid ViconResult");
  }
}

FABRIC_EXT_EXPORT void ViconResultAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam this_
)
{
  ViconDataStreamSDK::CPP::Result::Enum resultEnum;
  if (conv_from_KLStruct(this_, resultEnum))
  {
    _result = ResultEnumToString(resultEnum);
  } else {
    _result = "Unknown";
    FABRIC_EXT_SETERROR_AND_RETURN("%s: %s", "ViconResultAsString", "Invalid ViconResult");
  }
}

FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconResultIsSuccess(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam this_
)
{
  ViconDataStreamSDK::CPP::Result::Enum resultEnum;
  if (conv_from_KLStruct(this_, resultEnum))
  {
    return (resultEnum == ViconDataStreamSDK::CPP::Result::Success);
  } else {
    FABRIC_EXT_SETERROR_AND_RETURN_VALUE(false, "%s: %s", "ViconResultIsSuccess", "Invalid ViconResult");
  }
}

FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconResultEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam b
)
{
  ViconDataStreamSDK::CPP::Result::Enum enumA;
  ViconDataStreamSDK::CPP::Result::Enum enumB;
  if (conv_from_KLStruct(a, enumA) && conv_from_KLStruct(b, enumB))
  {
    return (enumA == enumB);
  } else {
    FABRIC_EXT_SETERROR_AND_RETURN_VALUE(false, "%s: %s", "ViconResultEqual", "Invalid ViconResult");
  }
}

FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconResultNotEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconResult >::INParam b
)
{
  ViconDataStreamSDK::CPP::Result::Enum enumA;
  ViconDataStreamSDK::CPP::Result::Enum enumB;
  if (conv_from_KLStruct(a, enumA) && conv_from_KLStruct(b, enumB))
  {
    return (enumA != enumB);
  } else {
    FABRIC_EXT_SETERROR_AND_RETURN_VALUE(true, "%s: %s", "ViconResultNotEqual", "Invalid ViconResult");
  }
}


