#ifndef __KL2EDK_AUTOGEN_ViconClient_functions__
#define __KL2EDK_AUTOGEN_ViconClient_functions__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "ViconClient.h"
#include "ViconVersion.h"
#include "ViconStreamMode.h"
#include "ViconAxisMapping.h"
#include "ViconTimeCode.h"
#include "Vec3.h"
#include "Mat33.h"
#include "Quat.h"
#include "Euler.h"


// Defined at ./ViconClient.kl:18:1
FABRIC_EXT_EXPORT void ViconClientConstructor(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:19:1
FABRIC_EXT_EXPORT void ViconClientDestructor(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:21:1
FABRIC_EXT_EXPORT void ViconClientGetVersion(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconVersion >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:23:1
FABRIC_EXT_EXPORT void ViconClientConnect(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam hostName
);

// Defined at ./ViconClient.kl:24:1
FABRIC_EXT_EXPORT void ViconClientConnectToMulticast(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam hostName,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam multicastIP
);

// Defined at ./ViconClient.kl:25:1
FABRIC_EXT_EXPORT void ViconClientDisconnect(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:26:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconClientIsConnected(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:28:1
FABRIC_EXT_EXPORT void ViconClientStartTransmittingMulticast(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam serverIP,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam multicastIP
);

// Defined at ./ViconClient.kl:29:1
FABRIC_EXT_EXPORT void ViconClientStopTransmittingMulticast(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:31:1
FABRIC_EXT_EXPORT void ViconClientEnableSegmentData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam flag
);

// Defined at ./ViconClient.kl:35:1
FABRIC_EXT_EXPORT void ViconClientEnableMarkerData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam flag
);

// Defined at ./ViconClient.kl:39:1
FABRIC_EXT_EXPORT void ViconClientEnableUnlabeledMarkerData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam flag
);

// Defined at ./ViconClient.kl:43:1
FABRIC_EXT_EXPORT void ViconClientEnableDeviceData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam flag
);

// Defined at ./ViconClient.kl:47:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconClientIsSegmentDataEnabled(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:48:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconClientIsMarkerDataEnabled(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:49:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconClientIsUnlabeledMarkerDataEnabled(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:50:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconClientIsDeviceDataEnabled(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:52:1
FABRIC_EXT_EXPORT void ViconClientSetStreamMode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam mode
);

// Defined at ./ViconClient.kl:54:1
FABRIC_EXT_EXPORT void ViconClientSetAxisMapping(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconAxisMapping >::INParam map
);

// Defined at ./ViconClient.kl:55:1
FABRIC_EXT_EXPORT void ViconClientGetAxisMapping(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconAxisMapping >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::INParam this_
);

// Defined at ./ViconClient.kl:57:1
FABRIC_EXT_EXPORT void ViconClientGetFrame(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:58:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 ViconClientGetFrameNumber(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:60:1
FABRIC_EXT_EXPORT void ViconClientGetTimecode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconTimeCode >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:62:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 ViconClientGetLatencySampleCount(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:63:1
FABRIC_EXT_EXPORT void ViconClientGetLatencySampleName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
);

// Defined at ./ViconClient.kl:64:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Float64 ViconClientGetLatencySampleValue(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
);

// Defined at ./ViconClient.kl:65:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Float64 ViconClientGetLatencyTotal(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:67:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 ViconClientGetSubjectCount(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_
);

// Defined at ./ViconClient.kl:68:1
FABRIC_EXT_EXPORT void ViconClientGetSubjectName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
);

// Defined at ./ViconClient.kl:70:1
FABRIC_EXT_EXPORT void ViconClientGetSubjectRootSegmentName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject
);

// Defined at ./ViconClient.kl:71:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 ViconClientGetSegmentCount(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject
);

// Defined at ./ViconClient.kl:72:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
);

// Defined at ./ViconClient.kl:74:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 ViconClientGetSegmentChildCount(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:75:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentChildName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam index
);

// Defined at ./ViconClient.kl:76:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentParentName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:78:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentStaticTranslation(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:79:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentStaticRotationHelical(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:80:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentStaticRotationMatrix(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat33 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:81:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentStaticRotationQuaternion(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Quat >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:82:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentStaticRotationEulerXYZ(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Euler >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:84:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentGlobalTranslation(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:85:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentGlobalRotationHelical(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:86:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentGlobalRotationMatrix(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat33 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:87:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentGlobalRotationQuaternion(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Quat >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:88:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentGlobalRotationEulerXYZ(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Euler >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:90:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentLocalTranslation(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:91:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentLocalRotationHelical(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:92:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentLocalRotationMatrix(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat33 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:93:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentLocalRotationQuaternion(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Quat >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

// Defined at ./ViconClient.kl:94:1
FABRIC_EXT_EXPORT void ViconClientGetSegmentLocalRotationEulerXYZ(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Euler >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconClient >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam subject,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam segment
);

#endif // __KL2EDK_AUTOGEN_ViconClient_functions__
