#ifndef __KL2EDK_AUTOGEN_ViconDataStream__
#define __KL2EDK_AUTOGEN_ViconDataStream__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

#include "ARGB.h"
#include "Box2.h"
#include "Box3.h"
#include "Color.h"
#include "Euler.h"
#include "Mat22.h"
#include "Mat33.h"
#include "Mat44.h"
#include "Quat.h"
#include "RGB.h"
#include "RGBA.h"
#include "Ray.h"
#include "RotationOrder.h"
#include "Vec2.h"
#include "Vec3.h"
#include "Vec3_d.h"
#include "Vec4.h"
#include "ViconAxisMapping.h"
#include "ViconClient.h"
#include "ViconClient_functions.h"
#include "ViconDirection.h"
#include "ViconDirection_functions.h"
#include "ViconResult.h"
#include "ViconResult_functions.h"
#include "ViconStreamMode.h"
#include "ViconStreamMode_functions.h"
#include "ViconTimeCode.h"
#include "ViconTimeCodeStandard.h"
#include "ViconTimeCodeStandard_functions.h"
#include "ViconVersion.h"
#include "Xfo.h"
#include "global_functions.h"

#endif // __KL2EDK_AUTOGEN_ViconDataStream__
