#ifndef __KL2EDK_AUTOGEN_ViconAxisMapping__
#define __KL2EDK_AUTOGEN_ViconAxisMapping__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "ViconDirection.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ViconAxisMapping'
// Defined at ./ViconAxisMapping.kl:6:1

struct ViconAxisMapping
{
  typedef ViconAxisMapping &Result;
  typedef ViconAxisMapping const &INParam;
  typedef ViconAxisMapping &IOParam;
  
  ViconDirection XAxis;
  ViconDirection YAxis;
  ViconDirection ZAxis;
};

inline void Traits<ViconAxisMapping>::ConstructEmpty( ViconAxisMapping &val )
{
  Traits< ViconDirection >::ConstructEmpty( val.XAxis );
  Traits< ViconDirection >::ConstructEmpty( val.YAxis );
  Traits< ViconDirection >::ConstructEmpty( val.ZAxis );
}
inline void Traits<ViconAxisMapping>::ConstructCopy( ViconAxisMapping &lhs, ViconAxisMapping const &rhs )
{
  Traits< ViconDirection >::ConstructCopy( lhs.XAxis, rhs.XAxis );
  Traits< ViconDirection >::ConstructCopy( lhs.YAxis, rhs.YAxis );
  Traits< ViconDirection >::ConstructCopy( lhs.ZAxis, rhs.ZAxis );
}
inline void Traits<ViconAxisMapping>::AssignCopy( ViconAxisMapping &lhs, ViconAxisMapping const &rhs )
{
  Traits< ViconDirection >::AssignCopy( lhs.XAxis, rhs.XAxis );
  Traits< ViconDirection >::AssignCopy( lhs.YAxis, rhs.YAxis );
  Traits< ViconDirection >::AssignCopy( lhs.ZAxis, rhs.ZAxis );
}
inline void Traits<ViconAxisMapping>::Destruct( ViconAxisMapping &val )
{
  Traits< ViconDirection >::Destruct( val.ZAxis );
  Traits< ViconDirection >::Destruct( val.YAxis );
  Traits< ViconDirection >::Destruct( val.XAxis );
}
}}}

#endif // __KL2EDK_AUTOGEN_ViconAxisMapping__
