/*
 * Fabric Core 1.11.4
 * Vicon Datastream EDK wrap
 */

#include "ViconDataStream.h" // Automatically generated by kl2edk

using namespace Fabric::EDK;
IMPLEMENT_FABRIC_EDK_ENTRIES( ViconDataStream )