#ifndef __KL2EDK_AUTOGEN_ViconResult__
#define __KL2EDK_AUTOGEN_ViconResult__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ViconResult'
// Defined at ./ViconResult.kl:6:1

struct ViconResult
{
  typedef ViconResult &Result;
  typedef ViconResult const &INParam;
  typedef ViconResult &IOParam;
  
  Data handle;
  Boolean occluded;
};

inline void Traits<ViconResult>::ConstructEmpty( ViconResult &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
  Traits< Boolean >::ConstructEmpty( val.occluded );
}
inline void Traits<ViconResult>::ConstructCopy( ViconResult &lhs, ViconResult const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
  Traits< Boolean >::ConstructCopy( lhs.occluded, rhs.occluded );
}
inline void Traits<ViconResult>::AssignCopy( ViconResult &lhs, ViconResult const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
  Traits< Boolean >::AssignCopy( lhs.occluded, rhs.occluded );
}
inline void Traits<ViconResult>::Destruct( ViconResult &val )
{
  Traits< Boolean >::Destruct( val.occluded );
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_ViconResult__
