#ifndef __KL2EDK_AUTOGEN_ViconStreamMode__
#define __KL2EDK_AUTOGEN_ViconStreamMode__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ViconStreamMode'
// Defined at ./ViconStreamMode.kl:6:1

struct ViconStreamMode
{
  typedef ViconStreamMode &Result;
  typedef ViconStreamMode const &INParam;
  typedef ViconStreamMode &IOParam;
  
  Data handle;
};

inline void Traits<ViconStreamMode>::ConstructEmpty( ViconStreamMode &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<ViconStreamMode>::ConstructCopy( ViconStreamMode &lhs, ViconStreamMode const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<ViconStreamMode>::AssignCopy( ViconStreamMode &lhs, ViconStreamMode const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<ViconStreamMode>::Destruct( ViconStreamMode &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_ViconStreamMode__
