#ifndef __KL2EDK_AUTOGEN_ViconStreamMode_functions__
#define __KL2EDK_AUTOGEN_ViconStreamMode_functions__

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2exe version 1.11.4
////////////////////////////////////////////////////////////////

#include <Fabric/EDK/EDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 11
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "ViconStreamMode.h"


// Defined at ./ViconStreamMode.kl:11:1
FABRIC_EXT_EXPORT void ViconStreamModeFromString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::IOParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
);

// Defined at ./ViconStreamMode.kl:12:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 ViconStreamModeAsCode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam this_
);

// Defined at ./ViconStreamMode.kl:13:1
FABRIC_EXT_EXPORT void ViconStreamModeAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam this_
);

// Defined at ./ViconStreamMode.kl:14:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconStreamModeEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam b
);

// Defined at ./ViconStreamMode.kl:15:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean ViconStreamModeNotEqual(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam a,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::ViconStreamMode >::INParam b
);

#endif // __KL2EDK_AUTOGEN_ViconStreamMode_functions__
